### ISSUE TITLE
Gradle

### ISSUE THREAD

**Issue by intrigus** [NinjaPhase/PokeDroid#2]
Hi,
libgdx normally uses gradle to organize dependencies but I can't find any build.gradle in the repository.
Could you please add gradle or could you add instructions on how to get started with this project?

**Comment by NinjaPhase** [comment]
Hey, gradle usually is used to manage dependencies for libgdx however it's more for pulling latest and having multiple branches off one project.

Since currently i'm working on the windows implementation and it will be ported to android later, I am avoiding using gradle at this moment in time.
All libraries are provided in each project's lib folder, simply include these in your building process in IntelliJ, eclipse or command line (I will write a program to do this in master if you wish).

**Comment by intrigus** [comment]
Why are you avoiding gradle?

You could still use your old way of managing dependencies while other users could use gradle.

**Comment by NinjaPhase** [comment]
Hey man, I'm gonna add gradle integration into the project but this means restructuring it a little while, it should be done in about 20 minutes to an hour.

Honestly i'm just way too lazy to deal with gradle but since it's a request, it will be added.

**Comment by NinjaPhase** [comment]
Gradle support has been added.
